### ISSUE TITLE
Add in functionality for multivariate time series

### ISSUE THREAD

**Issue by sbruce23** [dylanward01/FrequencyBandAnalysis#14]
Incorporate the code at this repo: https://github.com/sbruce23/meba for the multivariate time series option.

**Comment by dylanward01** [comment]
This has been almost fully done for the simulation side of the app. It's only missing a download button as of now. It does still need to be fully integrated onto the file upload side- but that is a problem that will be conquered soon.

**Comment by dylanward01** [comment]
This has been done and fully merged into the application.
