### ISSUE TITLE
Adding summary table and p-value plot

### ISSUE THREAD

**Issue by sbruce23** [dylanward01/FrequencyBandAnalysis#2]
Add a tables containing summary results of frequencies tested and their significance along with a dot plot of the p-values over frequencies.  Make these such that they can be downloaded as a PDF file for ease of use.

**Comment by sbruce23** [comment]
For the univariate case, also include the table to test for time-varying dynamics within bands

**Comment by dylanward01** [comment]
Just leaving a note for myself on this. This was done for the univariate simulation side...we just have to migrate and include the code on the other facets of the app.

**Comment by dylanward01** [comment]
Finished! I haven't uploaded it yet- but this is done.
