### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by mohit-chhaparia** [dylanward01/FrequencyBandAnalysis#6]
The legend goes out of the box boundaries.

**Comment by dylanward01** [comment]
I believe I fixed this in the latest version of the uploaded code. The legend across each of the downloads seem to scale properly, and look much improved on my end. I don't want to close this until Mohit confirms that it looks good on his end- just to be sure.

**Comment by mohit-chhaparia** [comment]
Yes, it is resolved!
